### ISSUE TITLE
Test "should send photo" fails when executed locally

### ISSUE THREAD

**Issue by timjb** [klappvisor/haskell-telegram-api#27] opened 2016-05-11 21:48 UTC
My guess is that the hardcoded `file_id` in the test source code only works with @klappvisor's test bot.

**Comment by klappvisor** [comment] 2016-05-11 21:50
confirmed

**Comment by klappvisor** [comment] 2016-05-11 22:11
@timjb I have tried to redirect the photo to public channel to make it available. Could you please check is it still failing?

**Comment by timjb** [comment] 2016-05-11 22:21
It's still failing. Here's the response from `sendPhoto`:

    Left (FailureResponse {responseStatus = Status {statusCode = 400, statusMessage = "Bad Request"}, responseContentType = application/json, responseBody = "{\"ok\":false,\"error_code\":400,\"description\":\"Wrong file identifier was specified\"}"})

**Comment by klappvisor** [comment] 2016-05-12 19:41
@ hopefully #33 will fix it. (When you redirect photo to public chat, Telegram assigns new id to it)

**Comment by timjb** [comment] 2016-05-12 20:04
No, #33 didn't fix the tests for me. Now (with 759b647a4ecfeb44af452a937ebbaee1f7406452), I'm getting two failures:

>    should send photo with file_id FAILED [1]
>    ...
>    should send audio FAILED [2]

**Comment by klappvisor** [comment] 2016-05-12 20:06
well... at least it works for CI. I'll keep issue open

**Comment by klappvisor** [comment] 2016-05-18 23:12
should be fixed for images, since now tests upload image first and then send it again by id

**Comment by klappvisor** [comment] 2016-05-22 12:42
Changed audio test to follow the same logic as the test for photos, so now it should be fixed. Please reopen this issue, it it's still failing

**Closed by klappvisor** 2016-05-22 12:42 UTC
